name: Application Test

on:
  pull_request:
    branches:
      - '*'

env:
  IMAGE_NAME: aula-cicd

jobs:

  test:
    name: "Teste da Aplicação"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - "docker.io/python:3.12.1-bullseye"
          - "docker.io/python:3.11.9-bullseye"
          - "docker.io/python:3.10.14-bullseye"
    container:
      image: ${{ matrix.container }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: myuser
          POSTGRES_DB: mydb
    steps:
      - uses: actions/checkout@v4
      - name: "Install pip deps"
        run: pip install -r requirements.txt
      - name: "Run Migrations"
        run: python wrapped/manage.py migrate
      - name: "Run Tests"
        run: cd wrapped && python manage.py test -v 3


  build:
    name: "Construção do Container"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build the container image"
        run: docker build . --file Containerfile --tag $IMAGE_NAME:${GITHUB_SHA}